sudo: required
dist: trusty

language: ruby
rvm:
  - 2.4.1

cache: bundler

env:
  - SERVICE=rubocop
  - SERVICE=brakeman
  - SERVICE=bundle-audit
  - SERVICE=rspec

before_script:
  - uname -a
  - ruby -v
  - which ruby
  - psql -c 'create database educloud_test;' -U postgres

services:
  - postgresql

script:
  - if [ $SERVICE == 'bundle-audit' ]; then
    bundle exec bundle-audit update;
    bundle exec bundle-audit check;
    fi
  - if [ $SERVICE == 'brakeman' ]; then bundle exec brakeman -z --ensure-latest; fi
  - if [ $SERVICE == 'rubocop' ]; then bundle exec rubocop; fi
  - if [ $SERVICE == 'rspec' ]; then
    RAILS_ENV=test bundle exec rake db:migrate --trace;
    bundle exec rails db:test:prepare;
    bundle exec rspec spec/;
    fi
